<?php /*

This file contains internal information for the Zacky Installer.
Do NOT change. Removing it might prevent you from using the installer 
on this installation in the future.

---
QlpoOTFBWSZTWY39o0gAAJlfgEAQQId/8CHwDRC/79+7MAE5tShqnop5NNT00nkmIyZNA0ANGmQagTJijT9TRGBNNNAAANBqepG01IDaQ0DIADQeoAb3oRPoMUYrEAEXr7rdwLmEqSWkspwwqy5FDN9NDSMYMk0HdfETB98EVETWwM0g22OEqrYonSduiUIHoExVMNjQBT0Y99C0nC4CAwfIGJiYtSW4OXEGypEzlxvpNnjVGwratqxTAUBECNEmjpwvOBdC84iPBb2xbv8S2G9YueAw1obU7ro9Dds8mnkOgX6+KlJ+aiK+Zyopx7uALIuijQrENDlOorlSifEkTNYaFzkLQkg116w9pjg5w+swDJGAFlPMuxORYqhM3DJADHI0tqwsOKg9UkgKLWadKPpBVb3LTaJWUmZC5EDzNacMClIaWNtcZWESUEewToNh4u/i7kinChIRv7RpAA==

...

*/
